export default function Head() {
  return (
    <>
      <title>Reedon Web : Web development agency. We build website for businesses, bloggers and institutions at reasonable price</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.png" />
    </>
  )
}
